function Matrix = Vec2Skew(vector)
%% Create a skew symmetric matrix from a vector

Matrix = [   0      -vector(3)   vector(2);...
          vector(3)     0       -vector(1);...
         -vector(2)  vector(1)      0     ];